ardeois/graphql-codegen-typescript-mock-data

package.json
yarn.lock

There can be only one instance of `graphql` dependency, so we needed to move it to the `peerDependencies` section.

fix: move graphql to peer dependencies

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

This pr will add handler for `InputObjectTypeDefinition` in visitor config.

fix: handle input-object-type definitions

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

Add `__typename` property to mock data. This can be added if you set in
the config `addTypename: true`

fix: add __typename property

---

package.json
src/index.ts
yarn.lock

Because `toPascalCase` was dropped in GraphQL Codegen > 1.11.0, this plugin just crashes when used. This quick fix implements the removed `toPascalCase` helper into the codebase.

Fixes broken dependency `toPascalCase`

---

README.md
package.json
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts
yarn.lock

This PR is going to fix the issue with pascalCase error, initially committed by @keesvanlierop
Also, I extended that functionality to support upper case enums as well.
The other thing that was failing for me was a recursive nesting.
Check this schema
```graphql
type User {
id: Int!
username: String!
tasks: [Task!]!
}
type Task {
id: Int!
description: String
author: User!
status: TaskStatus!
}
```
so, when I create a mock of a task -> user mock will be created, but then user mock will create a task mock and this will run recursively until the stack can't hold it anymore.
Overrides won't help because they come **after** the mock is created so I switched to the getters, so they won't create a nested mock if there is an override.

Bugfix/Feature: pascalCase; Bugfix: recursive nesting

---

README.md
package.json
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts
yarn.lock

* Default casing of typenames to pascalCase for consistency with the `typescript` plugin - **this is a breaking change**
* Add configuration option `typenames` to allow customization of typenames casing
* Add `keep` value for preserving original casing of both enum values and typenames. Users who rely on the current behavior can use it to avoid having to adjust their code
* Adjust existing unit tests and add new ones
* Update doc
Consider bumping the version number to 0.4.0

Issue #16: default typename casing to pascalCase and add configuration option

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

We only supported `Date` scalars, but they can be more.
As we don't know the type of scalars, the easy way is to represent it as a string.
We could improve the support of custom scalar types through a config, but let's see that later
Fixes #17

fix: add support for custom scalar

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

This PR simply provides an option for users to specify the prefix that their mock builders will have.
Closes #22
Additional Context
Initially I tried to implement the addPrefix option, but I saw that when omitting the prefix, the generator function names collided with the name of the existing TS types from @graphql-codegen/typescript. That's why a prefix must always be present.
This PR makes sure t

feat: allow users to specify the `prefix` of mock builders

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

Some apps use custom scalar for date-related stuff. This caused issues with the way `graphql-codegen-typescript-mock-data` handles autogenerated data, since a "random string" (the current  default), may not always be what you need.
This PR allows you to define mapping from your custom scalars to a casual embedded generator, allowing you to specify exactly how your scalar's autogenerated value will be populated
Closes #20 
To make configuration simple, a few "shortcuts" were taken. Namely:
- the mapping only accepts a `casual` key (function or string) as a valid autogenerated value in order to align with the rest of the library
- if a function is passed, then it will be called with its default arguments, since providing custom parameters for a function through a YAML file, would complicate …

feat:  add `scalars` config option for custom GraphQL [scalar -> casual] mappings

---

package.json
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
yarn.lock

[indefinite](https://www.npmjs.com/package/indefinite) is able to find the correct indefinite article (`a` or `an`) for a given word.
It contains a list of irregular words for exceptions
BREAKING CHANGE: mock names for irregular words might change. Example:
- before: `aUpload`
- after: `anUpload`

feat: use `indefinite` to find the correct article

---

README.md

Now we use `indefinite`, it's now `anUpdateUserInput` instead of `aUpdateUserInput`

doc: update mock name

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts
yarn.lock

Related with: https://github.com/ardeois/graphql-codegen-typescript-mock-data/issues/28
Allows adding a prefix to the generated types, useful when your types are globally exported (i.e when using the generator add plugin) so you don't need to import them into your files and can call them directly.
@ardeois let me know if implementation looks ok, I can add a couple more tests and then update the README

Add config for prefixing types

---

README.md
package.json
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts
yarn.lock

Some `casual.xxx` generators can accept arguments.
To give more flexibility, the `scalars` config now accepts:
- a string for retrocompatibility
- an object `{generator: string, arguments: any[]}` to pass arguments to the casual function

feat(scalars): add support for custom scalar with arguments

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap

When `addTypename` is `true`, we should also add the property `__typename` in the return type

fix: add __typename to return type

---

.circleci/config.yml
README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

Hi, 
I need to generate a specific value for mock. This implementation enables me to use my custom value generator. eg.
config:
```yml
src/test/factory/graphql.ts:
plugins:
- add: "import { generateArrayBuffer } from '../generators';"
- typescript-mock-data:
typesFile: "../../shared/graphql/generated.ts"
enumValues: upper-case#upperCase
typenames: keep
addTypename: true
scalars:
ArrayBuffer:  generateArrayBuffer()
```
src/test/factory/graphql.ts
```ts
import { generateArrayBuffer } from '../generators;
export const anPakeProtocol = (overrides?: Partial<PakeProtocol>): PakeProtocol => {
return {
id: overrides && overrides.hasOwnProperty('id') ? overrides.id! : '1d6a9360-c92b-4660-8e5f-04155047bddc',
message: overrides && overrides.hasOwnProperty('message') ? overrides.message! : …
```

Added support for custom generator function

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

Some types were inconsistent when we had a type like `ABCType`.
The code was using `AbcType` but we were importing `ABCType`

fix: update type case in `import`

---

package.json

Bump graphql dependency to allow 15.x

fix: update graphql peer dependency

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

When GraphQL types had non-pascal-case typing, the usage of mock function was incorrect.
We forgot to apply the casing on type names
Thanks for @vitorcamachoo for reporting the issue and @ccblaisdell for the reproduction
Fixes #40

fix: wrong generation of typenames

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

When option `typesFile` was used, the `import` line was not
using `typesPrefix` for types
Also used objects in function parameters, as the current params were getting out of control

fix(typesPrefix): use typesPrefix in imports

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

Similar to `typesPrefix`, the option `enumsPrefix` is used to add a prefix to all enum type usages
Also add union type in unit tests to verify the behaviour
Fixes #51

feat: add enumsPrefix option

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

While these types should not be used very often, it can
happen another mock references a `Query` or `Mutation` type.
Which means we'll declare a property value with `aQuery` or
`aMutation`
That's why we need to define those types
Fixes #42

fix: generate Query and Mutation mocks

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap

For example : a type like VirtualBan would be wrongly written as VirtualIBAN

fix: wrong type generated when terminateCircularRelationships is true

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

A fix for https://github.com/ardeois/graphql-codegen-typescript-mock-data/pull/61
In `@graphql-codegen/typescript` enum values never preserve underscores, as a conscious decision: https://github.com/dotansimha/graphql-code-generator/issues/1569
This fix aligns with that decision.

fix: never preserve underscores for enum values

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/circular-mocks/create-mocks.ts
tests/circular-mocks/spec.ts
tests/circular-mocks/types.ts
tests/typescript-mock-data.spec.ts

```ts
export type A = {
B: B;
C: C;
};
export type B = {
A: A;
};
export type C = {
aCollection: A[];
};
export type D = {
A: A;
B: B;
};
```
In this situation, Type B in Type D should return object A once, not an empty object.
But now, in the process of creating type D, Type A is created first, and after calling Type B inside Type A, Type B inside Type D is recognized as the second call.
This appears to be a side effect, not the originally intended recursion prevention effect, in my opinion.
So I modified the recursive call prevention logic by converting the set object to an array with immutability.
@ardeois 
This library is very useful for testing in my project and I want this fix to be implemented quickly. thank you 👍🏼

fix: relationshipsToOmit bug when terminateCircularRelationships is true

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/circular-mocks/create-mocks.ts
tests/circular-mocks/spec.ts
tests/circular-mocks/types.ts
tests/typescript-mock-data.spec.ts

```ts
export type A = {
B: B;
C: C;
};
export type B = {
A: A;
};
export type C = {
aCollection: A[];
};
export type D = {
A: A;
B: B;
};
```
In this situation, Type B in Type D should return object A once, not an empty object.
But now, in the process of creating type D, Type A is created first, and after calling Type B inside Type A, Type B inside Type D is recognized as the second call.
This appears to be a side effect, not the originally intended recursion prevention effect, in my opinion.
So I modified the recursive call prevention logic by converting the set object to an array with immutability.
This PR is a followup of #77

feat: relationshipsToOmit bug when terminateCircularRelationships is true

---

.github/stale.yml

Add stale bot to automatically close issues that are inactive after 45 days

fix: add stale bot

---

package.json
yarn.lock

Add missing `tslib` dependency.
This dependency is necessary after rollup converted typescript to ES or commonjs

fix: add tslib dependency

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

Update the generator to make sure `listElementCount` is set to 1 when undefined The output was also different than before version `2.4.0` since `fieldName` changed when generating list items
This PR makes sure the output of generated files is the same as before if we don't touch `listElementCount` option

fix: listElementCount sometimes undefined

---

README.md
package.json
src/index.ts
src/mockValueGenerator.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/generateLibrary/faker/__snapshots__/spec.ts.snap
tests/generateLibrary/faker/spec.ts
tests/generateLibrary/schema.ts
tests/generateLibrary/types.ts
tests/globalSetup.ts
tests/typescript-mock-data.spec.ts
yarn.lock

closes #90, related #92
Add a new option `generateLibrary` to make faker available in addition to the existing casual.
casual dependents on the node API(e.g. fs) and cannot be made to work in the browser.
ref: https://github.com/ardeois/graphql-codegen-typescript-mock-data/issues/90
To simplify the code, we also added a class that returns the mock value generated by the library.

feat: add generatorLibrary options and allow faker to select

---

src/index.ts
tests/scalars/__snapshots__/spec.ts.snap
tests/scalars/schema.ts
tests/scalars/spec.ts
tests/scalars/types.ts

Only non-native scalars were supported by the `scalars` config. We now check if a custom scalar is defined for each native type
fixes #91

fix: custom generator for native scalars

---

README.md
package.json
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/enumValues/__snapshots__/spec.ts.snap
tests/enumValues/schema.ts
tests/enumValues/spec.ts
tests/typescript-mock-data.spec.ts
tsconfig.json
yarn.lock

There was some differences with typescript plugin when we were generating enum values. For example `_id` was transformed to `Id` by typescript plugin, but we were generating `_Id`
We now use the same logic as typescript plugin, and changed the default to use `change-case-all#pascalCase` as the `change-case-all` package supports a lot of case converter. We also use dynamic module resolution so you can pass anything in `enumValues` as long as it's compatible with `module#function` syntax
Fixes #82

fix(enumValues): update behaviour to match typescript plugin

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

Fixes #104 
This PR renames the `typename` config input to `typeNames` which matches the pattern used for other inputs.
This matches the naming conventions mentioned in the GQL Codegen docs here:
- https://the-guild.dev/graphql/codegen/docs/config-reference/naming-convention#upper-case-enum-values

Rename `typenames` to `typeNames`

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

- https://github.com/ardeois/graphql-codegen-typescript-mock-data/pull/77
In the previous PR, due to the immutability issue, the data structure was modified from set to array.
However, I found out late that it is possible to fix bugs while using Set.
I opened a fix PR because I was aware that there was a performance hit.

fix: Change the relationshipsToOmit data structure from Array to Set

---

src/index.ts
tests/perTypeFieldGeneration/__snapshots__/spec.ts.snap
tests/perTypeFieldGeneration/schema.ts
tests/perTypeFieldGeneration/spec.ts

Fixes #110 
Extends the use of `handleFieldGeneration` into the Enum generation. This ensures any options which contain custom field generation are also applied there.
Tests have been added to verify the behaviour.

Allow custom field generation for Enum types

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/enumValues/__snapshots__/spec.ts.snap
tests/enumValues/spec.ts
tests/perTypeFieldGeneration/__snapshots__/spec.ts.snap
tests/perTypeFieldGeneration/spec.ts
tests/typescript-mock-data.spec.ts

This PR adds support for `enumsAsTypes` when enums as TypeScript string union types are desired.
Relates to enhancement: #117

feat: add support for enumsAsTypes

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/enumValues/__snapshots__/spec.ts.snap
tests/enumValues/schema.ts
tests/enumValues/spec.ts
tests/typescript-mock-data.spec.ts

Update enum values generation when it contains underscores to match Typescript generator
- Will use `transformUnderscore` config for enum type name only
- Enum keys underscores are always transformed, whatever the config from `transformUnderscore`
Update generation when `enumsAsTypes` is `true`:
- We need to keep the value as is because it's the string value to be sent

fix: enum values update

---

README.md
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

As outlined in https://github.com/ardeois/graphql-codegen-typescript-mock-data/issues/128, this PR adds a config option `defaultNullableToNull`, that when enabled generates null per default for nullable fields.

implement defaultNullableToNull config option (#128)

---

.github/stale.yml

Increase number of days before an issue or PR becomes stale. I don't have much time to work on this project right now, so removing the stale label for a relevant issue that was not

fix: update stale bot

---

src/index.ts
tests/useImplementingTypesAndTerminateCircularRelationships/__snapshots__/spec.ts.snap
tests/useImplementingTypesAndTerminateCircularRelationships/schema.ts
tests/useImplementingTypesAndTerminateCircularRelationships/spec.ts

This should work to fix the issue I'm talking about in #140

fix: Error when using useImplementingTypes and terminateCircularRelationships at the same time

---

README.md
src/index.ts
tests/useTypeImports/__snapshots__/spec.ts.snap
tests/useTypeImports/schema.ts
tests/useTypeImports/spec.ts

Hello! I didn't see any contribution guidelines so I am just posting this in the hopes we can get this merged.  This adds support for [this typescript compiler option](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) 
Let me know what needs to be done to get this merged!  Thanks

feat(config): add import type support

---

src/index.ts
tests/typesPrefixAndTerminateCircularRelationships/__snapshots__/spec.ts.snap
tests/typesPrefixAndTerminateCircularRelationships/schema.ts
tests/typesPrefixAndTerminateCircularRelationships/spec.ts

Fixing when using `typesPrefix` and `terminateCircularRelationships` simultaneously, a type error occurred because typesPrefix was not applied in the type cast of an empty object.

fix: type error when using typesPrefix and terminateCircularRelationships

---

README.md
src/index.ts
tests/terminateCircularRelationshipsImmediately/__snapshots__/spec.ts.snap
tests/terminateCircularRelationshipsImmediately/schema.ts
tests/terminateCircularRelationshipsImmediately/spec.ts
tests/terminateCircularRelationshipsImmediately/types.ts

This value will make the mock not create a new Set of relationships to ignore and create a global Set. This will circumvent possible OOM due to large graphs.
fixes #126

feat(terminateCircularRelationships): Add 'immediate' as a value for the terminateCircularRelationships option

---

README.md
src/index.ts
tests/typeNamesMapping/schema.ts
tests/typeNamesMapping/spec.ts
tests/useTypeImports/__snapshots__/spec.ts.snap
tests/useTypeImports/schema.ts
tests/useTypeImports/spec.ts

This merge request gives you the ability to rename your types, for example if you have conflicts in type names you can use the `as NEWTYPENAME` to work around the type name conflict.

feat: rename types in config

---

package.json
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts
tsconfig.json
yarn.lock

This PR adds support for the 'oneOf' directive on input objects.
The generated mocking function is a little different than most others:
- It only accepts a non-Partial type as an override
- It picks an arbitrary fieldName/member from the input object and creates a default mock for that that field
In order to install `@graphql-tools/utils`, I needed to upgrade Typescript
Once I upgraded typescript, there were type errors for the 'indefinite' package, so I added the `@types/indefinite` package

Add support for oneOf directive

---

README.md
package.json
src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

This PR introduces two new configuration options, `includedTypes` and `excludedTypes`, to the `graphql-codegen-typescript-mock-data` plugin for enhanced control over mock data generation:
1. **`includedTypes` (Array of strings):**  
- Allows specifying an array of types to **include** in the mock generation.  
- Only the types listed in `includedTypes` will have mock data generated.
2. **`excludedTypes` (Array of strings):**  
- Allows specifying an array of types to **exclude** from the mock generation.  
- Types listed in `excludedTypes` will **not** have mock data generated.
3. **Precedence:**  
- If both `includedTypes` and `excludedTypes` are provided, `includedTypes` takes **precedence** over `excludedTypes`.
**1. `includedTypes` Example:**
```yaml
plugins:
- typescript-mock-data: …
```

feat: add includedTypes and excludedTypes options for selective mock generation

---

src/index.ts
tests/useImplementingTypesAndDefaultNullableToNull/__snapshots__/spec.ts.snap
tests/useImplementingTypesAndDefaultNullableToNull/schema.ts
tests/useImplementingTypesAndDefaultNullableToNull/spec.ts

Hi @ardeois , thank you for the great package!
When `useImplementingTypes` and `defaultNullableToNull` are used at the same time, the plugin outputs weird `|| || || ||` in generated fixtures. This PR fixes this problem.

Fix: handling useImplementingTypes and defaultNullableToNull

---

src/index.ts
tests/__snapshots__/typescript-mock-data.spec.ts.snap
tests/typescript-mock-data.spec.ts

Fixes https://github.com/ardeois/graphql-codegen-typescript-mock-data/issues/193
Skip `terminateCircularRelationships` logic for fields who's types are input objects with the `@oneOf` directive. This fixes the generation of incorrect code with type errors.

Fix type errors in generated code for nested input objects with @oneOf directive
